steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'us-west1-docker.pkg.dev/qwiklabs-gcp-03-a4aac130e514/my-repo/sample-node-app-image', '.' ]
images:
- 'us-west1-docker.pkg.dev/qwiklabs-gcp-03-a4aac130e514/my-repo/sample-node-app-image'
